const mobileStoreData = [
  {
    id: 16,
    name: "OnePlus 11R",
    type: "Smartphone",
    price: 799.99,
    processor: "Snapdragon 888+",
    memory: 256,
    battery: 4500,
    OS: "OxygenOS 13 (Android 14)",
    rating: 4.8,
    warranty: 2,
    description:
      "The OnePlus 11R features the powerful Snapdragon 888+ processor, a generous 256GB of storage, and a 4500mAh battery for lasting performance. With OxygenOS 13 on top of Android 14, it delivers a smooth and customizable user experience.",
    remainingUnits: 15,
    image: "https://m.media-amazon.com/images/I/613SAOPmLeL._SX679_.jpg",
  },
  {
    id: 7,
    name: "iPhone 15 Pro",
    type: "Smartphone",
    price: 1299.99,
    processor: "A16 Bionic",
    memory: 256,
    battery: 4000,
    OS: "iOS 16",
    rating: 4.9,
    warranty: 2,
    description:
      "The latest iPhone with an advanced A16 Bionic chip, stunning ProMotion display, and improved camera system.",
    remainingUnits: 8,
    image:
      "https://mylayby.co.nz/media/catalog/product/cache/f3909c84cc0b01542da25634e4effa6c/1/3/1309724_full.jpg",
  },
  {
    id: 17,
    name: "Realme Narzo N53",
    type: "Smartphone",
    price: 349.99,
    processor: "MediaTek Helio G80",
    memory: 128,
    battery: 5000,
    OS: "Realme UI 3.0 (Android 12)",
    rating: 4.2,
    warranty: 1.5,
    description:
      "The Realme Narzo N53 offers a balance of performance and affordability, equipped with a reliable MediaTek Helio G80 processor and a large 5000mAh battery.",
    remainingUnits: 25,
    image: "https://m.media-amazon.com/images/I/71DSxfKzkJL._SL1500_.jpg",
  },
  {
    id: 1,
    name: "iPhone 13",
    type: "Smartphone",
    price: 999.99,
    processor: "A15 Bionic",
    memory: 128,
    battery: 3095,
    OS: "iOS 15",
    rating: 4.5,
    warranty: 1,
    description:
      "The latest iPhone with a powerful A15 Bionic chip and advanced camera system.",
    remainingUnits: 50,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/1d174ef4-81d8-42de-a6d5-94a65b0a6f4821170553.jpg",
  },
  {
    id: 15,
    name: "Realme GT Neo 2",
    type: "Smartphone",
    price: 549.99,
    processor: "Snapdragon 870",
    memory: 128,
    battery: 5000,
    OS: "Realme UI 2.0",
    rating: 4.1,
    warranty: 1,
    description:
      "A gaming-focused phone with a high-refresh-rate display and powerful internals.",
    remainingUnits: 22,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/25b3a11c-0302-414a-85fc-95a163d0471e23150725.jpg",
  },
  {
    id: 2,
    name: "Samsung Galaxy S21",
    type: "Smartphone",
    price: 899.99,
    processor: "Exynos 2100 / Snapdragon 888",
    memory: 256,
    battery: 4000,
    OS: "Android 11",
    rating: 4.3,
    warranty: 2,
    description:
      "A flagship Android phone with a stunning display and versatile camera setup.",
    remainingUnits: 13,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/ad2a1bf2-1a64-4d24-b8c9-d975b9da535f22220822.jpg",
  },
  {
    id: 3,
    name: "Google Pixel 8 5G",
    type: "Smartphone",
    price: 799.99,
    processor: "Google Tensor 2",
    memory: 256,
    battery: 4800,
    OS: "Android 15",
    rating: 4.8,
    warranty: 2,
    description:
      "Introducing the Google Pixel 8 5G, powered by the advanced Google Tensor 2 processor, featuring a spacious 256GB storage, and a long-lasting 4800mAh battery. Capture moments in stunning detail with the upgraded camera system. Experience the latest Android 15 for a seamless and intuitive user interface.",
    remainingUnits: 15,
    image: "https://m.media-amazon.com/images/I/41QLJ2irBsL.jpg",
  },
  {
    id: 4,
    name: "OnePlus 9 Pro",
    type: "Smartphone",
    price: 899.99,
    processor: "Snapdragon 888",
    memory: 256,
    battery: 4500,
    OS: "OxygenOS 11",
    rating: 3.8,
    warranty: 2,
    description:
      "A flagship killer with a smooth 120Hz Fluid AMOLED display and Hasselblad-tuned cameras.",
    remainingUnits: 25,
    image: "https://m.media-amazon.com/images/I/61H5BvUlNeS._SX679_.jpg",
  },
  {
    id: 5,
    name: "Xiaomi Redmi Note 10",
    type: "Smartphone",
    price: 249.99,
    processor: "Snapdragon 678",
    memory: 64,
    battery: 5000,
    OS: "MIUI 12",
    rating: 3.2,
    warranty: 1.5,
    description:
      "A budget-friendly phone with a high-resolution camera and a large battery.",
    remainingUnits: 40,
    image:
      "https://www.tranza.com/content/images/thumbs/0013193_celular-xiaomi-redmi-10ds-64gb-blue_600.jpeg",
  },
  {
    id: 6,
    name: "iPhone 15",
    type: "Smartphone",
    price: 1099.99,
    processor: "Snapdragon 888",
    memory: 128,
    battery: 4500,
    OS: "Android 11",
    rating: 4.6,
    warranty: 2,
    description:
      "A compact powerhouse with a 120Hz OLED display and advanced camera features.",
    remainingUnits: 15,
    image:
      "https://media.ldlc.com/r1600/ld/products/00/06/06/41/LD0006064109.jpg",
  },
  {
    id: 0,
    name: "Oppo Reno 10 Pro",
    type: "Smartphone",
    price: 899.99,
    processor: "Snapdragon 8cx Gen 3",
    memory: 256,
    battery: 5000,
    OS: "ColorOS 13 (Android 15)",
    rating: 4.7,
    warranty: 2,
    description:
      "The Oppo Reno 10 Pro features a powerful Snapdragon 8cx Gen 3 processor, ample 256GB storage, and a robust 5000mAh battery. With ColorOS 13 on top of Android 15, it provides a sleek and user-friendly interface. Capture stunning moments with its advanced camera system.",
    remainingUnits: 6,
    image: "https://m.media-amazon.com/images/I/51OoXhWRbCL.jpg",
  },
  {
    id: 8,
    name: "iPhone SE (2022)",
    type: "Smartphone",
    price: 499.99,
    processor: "A15 Bionic",
    memory: 128,
    battery: 1821,
    OS: "iOS 15",
    rating: 3.1,
    warranty: 1.5,
    description:
      "The compact iPhone with the latest processor, perfect for those who prefer a smaller size.",
    remainingUnits: 30,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/74a9e89d-c5d4-40be-a7ba-d5e12b92b71422111306.jpg",
  },
  {
    id: 9,
    name: "ASUS ROG Phone 6",
    type: "Gaming Smartphone",
    price: 1099.99,
    processor: "Snapdragon 8cx Gen 2+",
    memory: 512,
    battery: 6000,
    OS: "ROG UI (Android 14)",
    rating: 4.9,
    warranty: 2,
    description:
      "Unleash the power of gaming with the ASUS ROG Phone 6. Equipped with the Snapdragon 8cx Gen 2+ processor, massive 512GB storage, and a colossal 6000mAh battery, it delivers an unrivaled gaming experience. The ROG UI based on Android 14 provides a customized interface for gamers.",
    remainingUnits: 12,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/ba464d07-6062-451c-812c-f2273f84803823220807.jpg",
  },
  {
    id: 10,
    name: "OnePlus Nord 2",
    type: "Smartphone",
    price: 549.99,
    processor: "MediaTek Dimensity 1200",
    memory: 128,
    battery: 4500,
    OS: "OxygenOS 11",
    rating: 4.2,
    warranty: 1.5,
    description:
      "A mid-range OnePlus phone with a powerful processor and a versatile camera system.",
    remainingUnits: 15,
    image:
      "https://d2xamzlzrdbdbn.cloudfront.net/products/341eed87-8ca8-48cf-8b89-535ed418906323051029.jpg",
  },
  {
    id: 11,
    name: "Xiaomi Mi 11 Ultra",
    type: "Smartphone",
    price: 1199.99,
    processor: "Snapdragon 888",
    memory: 256,
    battery: 5000,
    OS: "MIUI 12",
    rating: 4.7,
    warranty: 2,
    description:
      "An ultra-premium phone with a massive camera setup and a stunning AMOLED display.",
    remainingUnits: 12,
    image:
      "https://i01.appmifile.com/webfile/globalimg/products/pc/mi-11-ultra/pc-specs-header.png",
  },
  {
    id: 12,
    name: "Motorola Moto G Power",
    type: "Smartphone",
    price: 299.99,
    processor: "Snapdragon 662",
    memory: 64,
    battery: 5000,
    OS: "Android 11",
    rating: 2.6,
    warranty: 1,
    description:
      "A budget-friendly phone with a focus on battery life and performance.",
    remainingUnits: 25,
    image:
      "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61QVWPfp1pL.jpg",
  },
  {
    id: 13,
    name: "Samsung Galaxy A52s",
    type: "Smartphone",
    price: 449.99,
    processor: "Snapdragon 778G",
    memory: 128,
    battery: 4500,
    OS: "Android 11",
    rating: 4.4,
    warranty: 1.5,
    description:
      "A mid-range Samsung phone with a high-refresh-rate Super AMOLED display.",
    remainingUnits: 18,
    image: "https://m.media-amazon.com/images/I/91YGl7eTi1L._SL1500_.jpg",
  },
  {
    id: 14,
    name: "Sony Xperia 1 III",
    type: "Smartphone",
    price: 1299.99,
    processor: "Snapdragon 888",
    memory: 256,
    battery: 4500,
    OS: "Android 11",
    rating: 3.6,
    warranty: 2,
    description:
      "A premium phone with a 4K HDR OLED display and a versatile camera system.",
    remainingUnits: 21,
    image:
      "https://i5.walmartimages.com/seo/Sony-XPERIA-1-4G-smartphone-RAM-6-GB-Internal-Memory-128-microSD-slot-OLED-display-6-5-3840-x-1644-pixels-3x-rear-cameras-12-MP-MP-front-camera-8-pur_4d44fae7-796a-4e4d-8e66-24569a5bc5d9_1.c44bcac18d7895b7bcee984962d95e18.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  },
  {
    id: 18,
    name: "Samsung Galaxy M14 5G",
    type: "Smartphone",
    price: 349.99,
    processor: "Exynos 1200",
    memory: 128,
    battery: 5000,
    OS: "One UI 5.1 (Android 13)",
    rating: 4.5,
    warranty: 1.5,
    description:
      "The Samsung Galaxy M14 5G offers a balance of affordability and features, equipped with an efficient Exynos 1200 processor, 128GB storage, a large 5000mAh battery, and the intuitive One UI 5.1 on Android 13.",
    remainingUnits: 20,
    image: "https://m.media-amazon.com/images/I/81pmO0iVNhL._SL1500_.jpg",
  },
  {
    id: 19,
    name: "Xiaomi Poco F4",
    type: "Smartphone",
    price: 399.99,
    processor: "MediaTek Dimensity 1200",
    memory: 128,
    battery: 5000,
    OS: "MIUI 13",
    rating: 4.3,
    warranty: 1.5,
    description:
      "A budget-friendly Xiaomi phone with a powerful processor and impressive camera capabilities.",
    remainingUnits: 4,
    image:
      "https://www.notebookcheck.net/fileadmin/Notebooks/Xiaomi/Poco_X4_GT/4_zu_3_Teaser_News.jpg",
  },
  {
    id: 20,
    name: "Huawei Mate 40 Pro",
    type: "Smartphone",
    price: 1199.99,
    processor: "Kirin 9000",
    memory: 256,
    battery: 4400,
    OS: "EMUI 11",
    rating: 4.6,
    warranty: 2,
    description:
      "A premium Huawei phone with a Leica camera system and a curved-edge OLED display.",
    remainingUnits: 10,
    image: "https://m.media-amazon.com/images/I/4162OhKmMlL.jpg",
  },
  {
    id: 21,
    name: "Samsung Galaxy S22 Ultra",
    type: "Smartphone",
    price: 1499.99,
    processor: "Exynos 2200 / Snapdragon 8cx",
    memory: 512,
    battery: 5000,
    OS: "Android 13",
    rating: 4.8,
    warranty: 2,
    description:
      "The Samsung Galaxy S22 Ultra is a flagship powerhouse featuring an advanced Exynos 2200 or Snapdragon 8cx processor, a massive 512GB storage, a 5000mAh battery, and a versatile camera system with cutting-edge features.",
    remainingUnits: 20,
    image: "https://m.media-amazon.com/images/I/71PzXKXjz6L._SL1500_.jpg",
  },
  {
    id: 22,
    name: "Samsung Galaxy S23 5G",
    type: "Smartphone",
    price: 1599.99,
    processor: "Exynos 2300 / Snapdragon 8cx Gen 2",
    memory: 512,
    battery: 4800,
    OS: "Android 14",
    rating: 4.9,
    warranty: 2,
    description:
      "The Samsung Galaxy S23 5G is a cutting-edge flagship device with a powerful Exynos 2300 or Snapdragon 8cx Gen 2 processor, expansive 512GB storage, a 4800mAh battery, and advanced camera features for stunning photography and video capabilities.",
    remainingUnits: 15,
    image:
      "https://cdn03.ciceksepeti.com/cicek/kcm56049990-1/XL/samsung-galaxy-s23-fe-128-gb-samsung-turkiye-garantili-kcm56049990-1-cc2cb2ec3357448ea6b7c55cc10ccc54.jpg",
  },
  {
    id: 23,
    name: "Xiaomi Mi 11X",
    type: "Smartphone",
    price: 699.99,
    processor: "Snapdragon 870",
    memory: 256,
    battery: 4520,
    OS: "MIUI 13 (Android 12)",
    rating: 4.6,
    warranty: 1.5,
    description:
      "The Xiaomi Mi 11X is a powerful smartphone equipped with a Snapdragon 870 processor, generous 256GB storage, and a 4520mAh battery. Its MIUI 13 interface offers a smooth and customizable user experience.",
    remainingUnits: 18,
    image: "https://m.media-amazon.com/images/I/71VQXjN6R7S._SL1500_.jpg",
  },
  {
    id: 24,
    name: "Google Pixel 7a",
    type: "Smartphone",
    price: 499.99,
    processor: "Google Tensor",
    memory: 128,
    battery: 4680,
    OS: "Android 13",
    rating: 4.7,
    warranty: 2,
    description:
      "The Google Pixel 7a boasts the powerful Google Tensor processor, 128GB of storage, and a substantial 4680mAh battery. With the latest Android 13, it offers a seamless and intuitive user experience along with exceptional camera capabilities.",
    remainingUnits: 22,
    image: "https://m.media-amazon.com/images/I/81XiSpe-w5L._SL1500_.jpg",
  },
  {
    id: 25,
    name: "Samsung Galaxy Z Fold5 5G",
    type: "Foldable Smartphone",
    price: 1999.99,
    processor: "Exynos 2200 / Snapdragon 8cx Gen 2",
    memory: 512,
    battery: 4400,
    OS: "One UI 6.0 (Android 14)",
    rating: 4.9,
    warranty: 2,
    description:
      "Experience the future with the Samsung Galaxy Z Fold5 5G, featuring a foldable design, powerful Exynos 2200 or Snapdragon 8cx Gen 2 processor, expansive 512GB storage, and a 4400mAh battery. The device runs on One UI 6.0 based on Android 14 for a cutting-edge user experience.",
    remainingUnits: 1,
    image: "https://m.media-amazon.com/images/I/716pi7fRTpL._SL1500_.jpg",
  },
];

export default mobileStoreData;
